### ISSUE TITLE
Can't compile on OTP23

### ISSUE THREAD

**Issue by oltarasenko** [AgileAlpha/block_keys#11]
Looks like we've got the next problem. One of the dependencies (keccakf1600) can't be compiled on otp23, as it has a major change in erl_interface. (http://blog.erlang.org/OTP-23-Highlights/)

On the high level it looks like this:
```
$ mix compile
===> Compiling keccakf1600
 LD     keccakf1600.so
ld: library not found for -lerl_interface
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/name/proj/deps/keccakf1600/c_src/../priv/keccakf1600.so] Error 1
===> Hook for compile failed!
** (Mix) Could not compile dependency :keccakf1600, "/Users/name/.asdf/installs/elixir/1.10.3-otp-23/.mix/rebar3 bare compile --paths="/Users/name/proj/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile keccakf1600", update it with "mix deps.update keccakf1600" or clean it with "mix deps.clean keccakf1600"
```

The quick investigation shows that the problematic line is: https://github.com/hayesgm/erlang-keccakf1600/blob/master/c_src/Makefile#L92 and the following change fixes it:
`LDLIBS += -L"$(ERL_INTERFACE_LIB_DIR)" -le`

However, I have two questions:
1. Is there a way for us to get rid of this `keccakf1600` as it seems to be unrelated to generating mnemonic based keys at all and is used only in some bitcoin specific thing we don't need atm?
2. If the option 1 is not possible is what is the best way to patch the keccakf1600 so we can get it mergeble to BlockKeys?

**Comment by tzumby** [comment]
Hey @oltarasenko, thanks for opening this. I haven't tried to compile on OTP-23 yet. Let me think about this, I'll try to see if I can find a pure Erlang implementation or a Rust NIF I can use here for `keccakf1600`

**Comment by tzumby** [comment]
I'm working on replacing the `erlang-keccakf1600` dependency and replacing it with a Rust based NIF. I'm writing that NIF myself now and will cut a new release after that's ready.

I'm also looking into separating the Address portion into their own hex packages. I will cut a 2.0.0 release for that once ready. There are a few cross dependencies there so I have to make sure the separation makes sense.

**Comment by oltarasenko** [comment]
@tzumby is there any way to move forward without RUST? We're a bit cautious regarding any external dependencies, and would want to avoid that as long as possible. 

The core functionality we're interested in the possibility to generate keys based on entropy/mnemonic and use it for signing. The bitcoin/ethereum parts seem to be unrelated. Also, keccakf1600 is used in Ethereum only.

Do you think it's possible to separate the bitcoin/ethereum things in a separate lib?

**Comment by oltarasenko** [comment]
I have made a patch to keccakf1600. Basically it should solve our problem: https://github.com/hayesgm/erlang-keccakf1600/pull/1
however I am not sure if it will be merged. The project seems to be a bit abandoned :(...

**Comment by tzumby** [comment]
I had the same feeling when I saw the repo, hasn't been tended to in a while. @viktmv patched our own fork with your fix and we'll be cutting a 0.1.4 release now that points to our fork. It should buy us some time to plan how we're going to organize this.

**Comment by tzumby** [comment]
@oltarasenko, we pushed a `0.1.5` release. Please let us know if it fixes the problem and I'll close this Issue

**Comment by oltarasenko** [comment]
Works for us now!
