### ISSUE TITLE
Unclear how to import the generated addresses on wallet

### ISSUE THREAD

**Issue by nicscl** [AgileAlpha/block_keys#32]
Hey!
I've been using this library and its great, we are testing it with testnet bitcoin, I cant seem to import the master private key on a wallet and match the generated addresses from the library, so I can’t spent.
I've tried P2PKH and derivation paths `m/44'/1'/0'`, `m/44'/0'/0'`, `m/0'/0'` and `m`.
Thanks in advance!

**Comment by tzumby** [comment]
Hey @nicscl! I can try and help you debug this. Just so I understand this correctly:

1) you are trying to import a master private key you created elsewhere (some other wallet I assume)
2) you read it with the library
3) you're trying to generate addresses on a particular path

If this is the case, have you confirmed the exact derivation path that the external wallet is using ? I see you listed a few of them

**Comment by tzumby** [comment]
This might come in handy as well: https://iancoleman.io/bip39/

I used it as I was writing this library to test that my encoding / decoding produced expected results

**Comment by nicscl** [comment]
Thanks, for the quick response @tzumby ,
I read a key that I generated from another program, and try to generate address, the path that I input to the library is `M/0/x` where x is a sequential integer, I cant seem to match the resulting addresses from `block_keys` on any wallet, and even in the  tool you sent me.
I am using:
```elixir
CKD.derive(key, path)
    |> from_pub()
```
to generate the addresses, where the key is the master public key, and the paths are unhardened.
The some private key I generated for this test: `tprv8ZgxMBicQKsPe5pcu54VwFTKrgu3oT5dy6HRpBHmz1JXEL7jveoCzEJEbmf7vt8ws8s3zwpenxYyDVkwzwvDAugami1uD6WxrUD74X3j6Cd`
This is using `block_keys`:
<img width="968" alt="Screen Shot 2021-06-28 at 18 29 37" src="https://user-images.githubusercontent.com/36410060/123706578-d2bb6300-d83e-11eb-92dc-409d2ff2464d.png">
This is using the site:
<img width="414" alt="Screen Shot 2021-06-28 at 18 31 27" src="https://user-images.githubusercontent.com/36410060/123706761-11e9b400-d83f-11eb-9850-2d307b1408d5.png">

**Comment by tzumby** [comment]
What is the expected address at `M/0/0` ? 

I think the right way to get the master public key from the master private is:

```
xpub = BlockKeys.CKD.master_public_key("tprv8ZgxMBicQKsPe5pcu54VwFTKrgu3oT5dy6HRpBHmz1JXEL7jveoCzEJEbmf7vt8ws8s3zwpenxYyDVkwzwvDAugami1uD6WxrUD74X3j6Cd")

BlockKeys.Bitcoin.address(xpub, "M/0/0")
"12r8UVsRn39tuE9sngP4jrD6oUjnXUVRSt"
```

**Comment by nicscl** [comment]
Thanks for the response,
So, `"tprv8ZgxMBi...` is a testnet prefixed key, but `12r8UVsRn39tuE9sngP4jrD6oUjnXUVRSt` a mainnet address right? Thats why I used the libraries directly, I believe this seems to be an issue, and I'd be happy to open a PR or an issue for it!
But, getting the master pub key and then deriving the addresses yield the same result:
<img width="1149" alt="Screen Shot 2021-06-29 at 10 58 37" src="https://user-images.githubusercontent.com/36410060/123810822-16f34580-d8c9-11eb-8b14-b1f2283852a9.png">
Which is how its supposed to be.
My question realy is about this part of the doc:
<img width="867" alt="Screen Shot 2021-06-29 at 11 03 40" src="https://user-images.githubusercontent.com/36410060/123811527-b44e7980-d8c9-11eb-8c23-7677ff275735.png">
Is there a base derivation path that this library uses when deriving addresses, so when I input `M/0/0` it actually means something else?
